version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"   # Diretório raiz onde está o package.json
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
